### PR TITLE
Add a way to configure to use Authorization: Bearer header instead of cookie

### LINKED ISSUE #2: Authorization: Bearer
Hi there, I'm just getting started with Nickel and I'm super interested in your plugin, can even try and assist with improvements/etc. Is it possible through the current API to get the jwt as a Authorization: Bearer <xxx> header?

### PR DESCRIPTION
**Pull request by carols10cents**
Fixes #2.

Please let me know if you'd like me to change anything! This also had the nice side effect of making it easy to customize the cookie name.

### CODE REVIEW

**Comment by kaj** [comment]
Thank you for your contribution!  The code seems clean and I like the extended README.

I haven't used the Authorization header much myself, so I have a rather basic question: wouldn't some real servers want to support both at the same time, allowing some requests to authorize by cookie while others use the authorization header?  If so, would that be hard to add on these changes?   Maybe that could simply be a third alternative in `enum TokenLocation`?

**Comment by stephanbuys** [comment]
@kaj, we've only used Authorization Bearer, @carols10cents is it a big change to add the 3rd option as suggested (does it make sense? I'm also unsure)? If it makes sense, lets do it. @kaj, I'm looking forward to using this - would be great if you could merge, but also looking to improve the Rust OSS ecosystem, so definitely open to looking at what would make sense.

**Comment by kaj** [comment]
I've been thinking a bit more, and even _if_ we should have that third alternative I think it makes more sense to add it as an explicit third alternative in `TokenLocation` rather than having an indenpendent toggle for each method.  And that third alternative can always be added later, if and when someone asks for it.

So I'll just merge this and push out a release.

@carols10cents, given how small this package was before your contribution, you have actually written close to half the package. :-)   I'll be happy to add your name to the authors list in `Cargo.toml` if you want to?

**Comment by carols10cents** [comment]
Yeah, i'm not sure how common this is, but I did find this [jwt middleware for caddy](https://github.com/BTBurke/caddy-jwt#ways-of-passing-a-token-for-validation) that looks for clients sending tokens in the Authentication: Bearer header, then a cookie, then a query parameter even! So there could be more to do, depending on what people need :)

I'd be honored to be in the `Cargo.toml`, thank you! ❤️

**Comment by kaj** [comment]
Ok, I think we consider this done for now.  I have merged it and will push out a release.  Then we can decide if we want to add bearer-and-cookie as an additional method, or add query parameter support and possibly let the user specify a list of methods (that way, the user also specifies the prioritization order between the methods, which may be a good thing).

**Comment by carols10cents** [comment]
Yay! 🎉

**Pull request merged**
