### PR TITLE
Custom claims

### PR DESCRIPTION
**Pull request by carols10cents**
This is another feature request that @stephanbuys is commissioning :) Stephan, please let me know if this works for your use case!

This PR adds methods to enable users of nickel-jwt-session to set and retrieve arbitrary claims payload data in the token rather than just the username. I debated removing the username methods but decided to enhance the existing API instead of replacing.

nickel-jwt-session will still be managing the `jwt::Registered` fields that it was already (exp and nbf). I could see another enhancement in the future being to expose that as well, perhaps unifying the set/get functions into ones that take and return `jwt::Claims` or `(Option<jwt::Registered>, Option<BTreeMap<String, Json>>)` or something, but Stephan only needs to customize the data for now.

Looking forward to your feedback!

### CODE REVIEW

**Comment by kaj** [comment]
Hello again!  Sorry for my long absence, I was on vacation with very limited network access.

I think both the API and the example should be clear that the registered and custom claims can (and often should) be used together, so
1. Please make the example store the user id in the registered field and some extra information (maybe a real name as well as the admin flag you have added) as custom fields.
2. I think the `clear_jwt_user` and `clear_jwt_custom_claims` should be dropped, and `clear_jwt` instead be added to `trait SessionResponseExtensions`.

Other than that, this seems great.  I especially appreciate your attention to documentation!

**Comment by carols10cents** [comment]
And sorry for my slow response, I was out of town after you! :) 

I've added a commit for your 2nd suggestion, that makes it way better! 

I'm not sure what you mean exactly for your 1st suggestion and decided to check with you before I guessed and tried something:

> Please make the example store the user id in the registered field and some extra information

Do you mean that someone using nickel-jwt-session in their app should be able to call _both_ `set_jwt_user()` and `set_jwt_custom_claims()` in the same request, and have the information added to the token if these methods see that a token already exists?

Or do you mean that if we call `set_jwt_custom_claims()`, `make_token_custom_claims()` should extract something from the `BTreeMap` and store it as the `sub` registered field? I don't think we can assume anything about the values in the `custom_claims` (there might not be anything that looks like a user id), but we could make a documented optional default of `user` or `user_id`  or something have this behavior and set the `sub` value if that key is present in the `BTreeMap`.

Or do you mean that `set_jwt_custom_claims()` should take an additional argument `user: &str`? If so, I think this should be an `Option<&str>`, similarly because there may be use cases that might not have a user id-ish thing.

Or something else? Please let me know, thank you for your comments!

**Comment by kaj** [comment]
> I've added a commit for your 2nd suggestion, that makes it way better!

Great!

> Do you mean that someone using nickel-jwt-session in their app should [a or b or c]

I don't really know what I mean, other than that it should be possible to set both the registered `sub` field and any custom fields in the same token.

How about this:  Combine `make_token` and `make_token_custom_claims` in `SessionMiddleware` to a `make_token(&self, user: Option<&str>, custom_claims: BTreeMap<String, Json>)`, but make three different methods in `SessionResponseExtensions`, one for username only, one for custom claims only and one for both.

**Comment by carols10cents** [comment]
> How about this: Combine make_token and make_token_custom_claims in SessionMiddleware to a make_token(&self, user: Option<&str>, custom_claims: BTreeMap<String, Json>), but make three different methods in SessionResponseExtensions, one for username only, one for custom claims only and one for both.

I like it! I've added a commit to do that, and updated the custom claims example to use it, let me know what you think!

**Comment by kaj** [comment]
Yes, I like this version!  Possibly a bit too much repeated code in the set_jwt_\* methods, but that can always be fixed later ...

I'll look some more, and if I don't find any more problems, I'll merge and try to put out a new release soonish.

**Comment by iamsebastian** [comment]
@kaj 
How about a fresh release?

**Comment by kaj** [comment]
Released 0.4.0.  Sorry for the delay, @iamsebastian

**Comment by iamsebastian** [comment]
You're very welcome, @kaj. Thanks.

**Pull request merged**
